--- #YAML:1.0
name:               XML-Parser-Nodes
version:            0.01
abstract:           Extends XML::Parser
author:
    - Jim Schueler <jim@tqis.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    XML::Dumper:  0.81
    XML::Parser:  2.36
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
